# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0005_auto_20170105_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naprava',
            options={'permissions': (('edit_naprava', 'Can edit naprava'),)},
        ),
    ]
