# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0004_auto_20170105_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='naprava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.Naprava'),
        ),
    ]
